# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvK0ZenoVq5U0JvX2TNqIe3l-Tp2x6Kx
"""

import json, subprocess, sys

factory_cmd = sys.argv[1]
belts_cmd = sys.argv[2]

sample_factory = {
  "machines": {
    "assembler_1": {"crafts_per_min": 30},
    "chemical": {"crafts_per_min": 60}
  },
  "recipes": {
    "iron_plate": {
      "machine": "chemical",
      "time_s": 3.2,
      "in": {"iron_ore": 1},
      "out": {"iron_plate": 1}
    },
    "copper_plate": {
      "machine": "chemical",
      "time_s": 3.2,
      "in": {"copper_ore": 1},
      "out": {"copper_plate": 1}
    },
    "green_circuit": {
      "machine": "assembler_1",
      "time_s": 0.5,
      "in": {"iron_plate": 1, "copper_plate": 3},
      "out": {"green_circuit": 1}
    }
  },
  "modules": {
    "assembler_1": {"prod": 0.1, "speed": 0.15},
    "chemical": {"prod": 0.2, "speed": 0.1}
  },
  "limits": {
    "raw_supply_per_min": {"iron_ore": 5000, "copper_ore": 5000},
    "max_machines": {"assembler_1": 300, "chemical": 300}
  },
  "target": {"item": "green_circuit", "rate_per_min": 1800}
}

sample_belts = {
    "nodes": ["s1","s2","a","b","c","sink"],
    "edges": [
        {"from":"s1","to":"a","lo":0,"hi":900},
        {"from":"a","to":"b","lo":0,"hi":900},
        {"from":"b","to":"sink","lo":0,"hi":900},
        {"from":"s2","to":"a","lo":0,"hi":600},
        {"from":"a","to":"c","lo":0,"hi":600},
        {"from":"c","to":"sink","lo":0,"hi":600}
    ],
    "sources": {"s1":900,"s2":600},
    "sink": "sink",
    "node_caps": {"a": 2000, "b": 2000, "c": 2000}
}

def run(cmd, obj):
    p = subprocess.run(cmd.split(), input=json.dumps(obj).encode(), stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
    print(p.stdout.decode())

run(factory_cmd, sample_factory)
run(belts_cmd, sample_belts)